### ISSUE TITLE
poll creating error

### ISSUE THREAD

**Issue by ssydorov** [matterpoll/matterpoll#143]
/pool

error on the client side:
Received invalid response from the server.

error in the server log /opt/mattremost/logs:
{"level":"error","ts":1554119248.0470464,"caller":"plugin/client_rpc_generated.go:102","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"connection is shut down"}
{"level":"error","ts":1554119248.0471678,"caller":"app/server.go:62","msg":"Please check the std error output for the stack trace"}
{"level":"error","ts":1554119248.0471935,"caller":"app/server.go:63","msg":"[runtime error: invalid memory address or nil pointer dereference]"}

error in /var/log/messages

```
Apr  1 14:54:28 kielxmatter01 mattermost: {"level":"error","ts":1554119668.0518687,"caller":"plugin/client_rpc_generated.go:102","msg":"RPC call ExecuteCommand to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"connection is shut down"}
Apr  1 14:54:28 kielxmatter01 mattermost: {"level":"error","ts":1554119668.0519633,"caller":"app/server.go:62","msg":"Please check the std error output for the stack trace"}
Apr  1 14:54:28 kielxmatter01 mattermost: {"level":"error","ts":1554119668.0519865,"caller":"app/server.go:63","msg":"[runtime error: invalid memory address or nil pointer dereference]"}
Apr  1 14:54:28 kielxmatter01 mattermost: goroutine 9946378 [running]:
Apr  1 14:54:28 kielxmatter01 mattermost: runtime/debug.Stack(0x0, 0x0, 0x129f600)
Apr  1 14:54:28 kielxmatter01 mattermost: /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Apr  1 14:54:28 kielxmatter01 mattermost: runtime/debug.PrintStack()
Apr  1 14:54:28 kielxmatter01 mattermost: /usr/local/go/src/runtime/debug/stack.go:16 +0x22
Apr  1 14:54:28 kielxmatter01 mattermost: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.log(0x172d160, 0xc420250000, 0x172ce20, 0x20b6b28, 0x1, 0xc429e25800, 0x1, 0x1)
Apr  1 14:54:28 kielxmatter01 mattermost: /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:89 +0x70
Apr  1 14:54:28 kielxmatter01 mattermost: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x1738ec0, 0xc424ded420, 0x172d160, 0xc420250000, 0x172ce20, 0x20b6b28, 0x1)
Apr  1 14:54:28 kielxmatter01 mattermost: /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:74 +0xe5
Apr  1 14:54:28 kielxmatter01 mattermost: panic(0x1354b00, 0x205a1e0)
Apr  1 14:54:28 kielxmatter01 mattermost: /usr/local/go/src/runtime/panic.go:502 +0x229
Apr  1 14:54:28 kielxmatter01 mattermost: github.com/mattermost/mattermost-server/app.(*App).HandleCommandResponse(0xc4200f6580, 0xc4238c22d0, 0xc4273d6480, 0x0, 0x1, 0xc4282b8a00, 0x3)
Apr  1 14:54:28 kielxmatter01 mattermost: /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/command.go:277 +0x10d
Apr  1 14:54:28 kielxmatter01 mattermost: github.com/mattermost/mattermost-server/app.(*App).ExecuteCommand(0xc4200f6580, 0xc4273d6480, 0x0, 0x0)
Apr  1 14:54:28 kielxmatter01 mattermost: /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/command.go:171 +0x2205
Apr  1 14:54:28 kielxmatter01 mattermost: github.com/mattermost/mattermost-server/api4.executeCommand(0xc424471300, 0x1738ec0, 0xc424ded420, 0xc424471200)
Apr  1 14:54:28 kielxmatter01 mattermost: /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/api4/command.go:227 +0x35f
Apr  1 14:54:28 kielxmatter01 mattermost: github.com/mattermost/mattermost-server/web.Handler.ServeHTTP(0xc4200f6580, 0x15d2fb0, 0x10001, 0x1738ec0, 0xc424ded420, 0xc424471200)
Apr  1 14:54:28 kielxmatter01 mattermost: /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/web/handlers.go:131 +0x126d
Apr  1 14:54:28 kielxmatter01 mattermost: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420250000, 0x1738ec0, 0xc424ded420, 0xc424471200)
Apr  1 14:54:28 kielxmatter01 mattermost: /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162 +0xed
Apr  1 14:54:28 kielxmatter01 mattermost: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x172d160, 0xc420250000, 0x172ce20, 0x20b6b28, 0x1, 0x1738ec0, 0xc424ded420, 0xc424471000)
Apr  1 14:54:28 kielxmatter01 mattermost: /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78 +0xb9
Apr  1 14:54:28 kielxmatter01 mattermost: net/http.serverHandler.ServeHTTP(0xc4220a8d00, 0x1738ec0, 0xc424ded420, 0xc424471000)
Apr  1 14:54:28 kielxmatter01 mattermost: /usr/local/go/src/net/http/server.go:2694 +0xbc
Apr  1 14:54:28 kielxmatter01 mattermost: net/http.(*conn).serve(0xc427e13220, 0x1739f80, 0xc427f35640)
Apr  1 14:54:28 kielxmatter01 mattermost: /usr/local/go/src/net/http/server.go:1830 +0x651
Apr  1 14:54:28 kielxmatter01 mattermost: created by net/http.(*Server).Serve
Apr  1 14:54:28 kielxmatter01 mattermost: /usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Comment by hanzei** [comment]
@ssydorov Could you please provide more information about your installation?

- **Operating system:**

- **Mattermost version:**

- **Matterpoll version:**

- **Updated from an older Matterpoll version or fresh install:**

Did you made sure your sideURL is set?

**Comment by ssydorov** [comment]
yes, of course

Operating system: 
Centos 7

Mattermost version: 
Version: 5.3.0
Build Number: 5.3.1
Build Date: Wed Sep 19 07:42:34 UTC 2018
Build Hash: fd21e53365d504155ab87f9bef60b1ab4faeb38d
Build Enterprise Ready: true
DB Version: 5.3.0

Matterpoll version:
com.github.matterpoll.matterpoll-1.0.3.tar.gz

Updated from an older Matterpoll version or fresh install:
fresh install

Did you made sure your sideURL is set?
yes

**Comment by ssydorov** [comment]
hi
I updated mattremost to 5.9  and now poll is working. thanks1
