### ISSUE TITLE
Cannot close poll when default language of server is polish

### ISSUE THREAD

**Issue by amz** [matterpoll/matterpoll#252]
#### Summary
Cannot close poll

#### Steps to reproduce
1. Cannot close poll
2. Error ocurres

#### Expected behavior
Can close poll

#### Observed behavior (that appears unintentional)
After confirming closing in popup http request is made to:
/api/v4/actions/dialogs/submit with emtpy {} response and http status 200

In admin console -> plugin management i can see:
Matterpoll (com.github.matterpoll.matterpoll - 1.3.0)
This plugin crashed multiple times and is no longer running. Check your system logs for errors.

#### Server configuration
**Operating system:**
Ubuntu 18.04.3
**Mattermost version:**
5.18.1
**Matterpoll version:**
1.3.0
**Updated from an older Matterpoll version or fresh install:**
Updated from 5.14. At 5.14 was similar problem
<details>
<summary>Mattermost server logs</summary>

```
Jan 10 20:10:54 localhost mattermost[35696]: {"level":"debug","ts":1578687054.2560847,"caller":"mlog/sugar.go:15","msg":"New request:","plugin_id":"com.github.matterpoll.matterpoll","Host":"","RequestURI":"","Method":"POST"}
Jan 10 20:10:54 localhost mattermost[35696]: {"level":"debug","ts":1578687054.7189283,"caller":"web/handlers.go:77","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"cnhorea46t8kpkb9dn53hifa3r"}
Jan 10 20:10:55 localhost mattermost[35696]: {"level":"debug","ts":1578687055.574891,"caller":"web/handlers.go:77","msg":"Received HTTP request","method":"POST","url":"/api/v4/users/status/ids","request_id":"bzsm7kc6aj8zip1a9my3371m6w"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.679782,"caller":"web/handlers.go:77","msg":"Received HTTP request","method":"POST","url":"/api/v4/actions/dialogs/submit","request_id":"xbd83y3xjpbrzfy6r9anwu9yya"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6808593,"caller":"mlog/sugar.go:15","msg":"New request:","plugin_id":"com.github.matterpoll.matterpoll","Host":"","RequestURI":"","Method":"POST"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6895978,"caller":"plugin/hclog_adapter.go:35","msg":"panic: message \"poll.endPost.answer.heading\" has no plural form \"few\"","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6896212,"caller":"plugin/hclog_adapter.go:35","msg":"","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6896462,"caller":"plugin/hclog_adapter.go:35","msg":"goroutine 33 [running]:","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6896522,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).MustLocalize(0xc0000c77c0, 0xc0000c76a0, 0xbbfedb, 0x5)","plugin_id":"com.github.matterpo
ll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6896574,"caller":"plugin/hclog_adapter.go:35","msg":"\t/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.2/i18n/localizer.go:231 +0x7a","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6897218,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/matterpoll/matterpoll/server/poll.(*Poll).ToEndPollPost(0xc00033db00, 0xc0003cf7c0, 0xc0003a6980, 0x9, 0xc0003cf7a0, 0x1, 0x148)"
,"plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6897328,"caller":"plugin/hclog_adapter.go:35","msg":"\t/home/circleci/project/server/poll/transform.go:154 +0x2f6","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6897407,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/matterpoll/matterpoll/server/plugin.(*MatterpollPlugin).handleEndPollConfirm(0xc000122600, 0xc0003f2180, 0xc000107580, 0xa99740, 
0xcb4e40, 0xad0fa0, 0xc0003f2180)","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6897478,"caller":"plugin/hclog_adapter.go:35","msg":"\t/home/circleci/project/server/plugin/api.go:397 +0x21e","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.690234,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/matterpoll/matterpoll/server/plugin.(*MatterpollPlugin).handleSubmitDialogRequest.func1(0xcd50c0, 0xc0003a0f60, 0xc00012c800)","pl
ugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6902535,"caller":"plugin/hclog_adapter.go:35","msg":"\t/home/circleci/project/server/plugin/api.go:179 +0xca","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6902606,"caller":"plugin/hclog_adapter.go:35","msg":"net/http.HandlerFunc.ServeHTTP(0xc00031dfa0, 0xcd50c0, 0xc0003a0f60, 0xc00012c800)","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6902676,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/net/http/server.go:1995 +0x44","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6902738,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/matterpoll/matterpoll/server/plugin.checkAuthenticity.func1(0xcd50c0, 0xc0003a0f60, 0xc00012c800)","plugin_id":"com.github.matter
poll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6902792,"caller":"plugin/hclog_adapter.go:35","msg":"\t/home/circleci/project/server/plugin/api.go:135 +0xd5","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6906576,"caller":"plugin/hclog_adapter.go:35","msg":"net/http.HandlerFunc.ServeHTTP(0xc0003b9780, 0xcd50c0, 0xc0003a0f60, 0xc00012c800)","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6906724,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/net/http/server.go:1995 +0x44","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6906815,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/gorilla/mux.(*Router).ServeHTTP(0xc000092f00, 0xcd50c0, 0xc0003a0f60, 0xc0000fc700)","plugin_id":"com.github.matterpoll.matterpol
l"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.690688,"caller":"plugin/hclog_adapter.go:35","msg":"\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe3","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6906946,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/matterpoll/matterpoll/server/plugin.(*MatterpollPlugin).ServeHTTP(0xc000122600, 0xc0000a7630, 0xcd50c0, 0xc0003a0f60, 0xc0000fc70
0)","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6907027,"caller":"plugin/hclog_adapter.go:35","msg":"\t/home/circleci/project/server/plugin/api.go:93 +0x1cd","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6907089,"caller":"plugin/hclog_adapter.go:35","msg":"github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).ServeHTTP(0xc00008f220, 0xc0003b62c0, 0x1207cd8, 0x0, 0x0)","plugin_id":"co
m.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6907527,"caller":"plugin/hclog_adapter.go:35","msg":"\t/go/pkg/mod/github.com/mattermost/mattermost-server@v5.14.0+incompatible/plugin/client_rpc.go:358 +0x293","plugin_id":"com.github.matterpo
ll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.690767,"caller":"plugin/hclog_adapter.go:35","msg":"reflect.Value.call(0xc00009d6e0, 0xc00009a940, 0x13, 0xbbdaea, 0x4, 0xc00004ff18, 0x3, 0x3, 0xc00022a200, 0xaf4400, ...)","plugin_id":"com.gi
thub.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6907763,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/reflect/value.go:447 +0x461","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6907966,"caller":"plugin/hclog_adapter.go:35","msg":"reflect.Value.Call(0xc00009d6e0, 0xc00009a940, 0x13, 0xc000043718, 0x3, 0x3, 0xc00009c5a0, 0xc0000436c0, 0x2)","plugin_id":"com.github.matte
rpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6908054,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/reflect/value.go:308 +0xa4","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6908298,"caller":"plugin/hclog_adapter.go:35","msg":"net/rpc.(*service).call(0xc00024e240, 0xc0000a67d0, 0xc000098ce0, 0xc000098cf0, 0xc000106a00, 0xc00008fd20, 0xa76540, 0xc0003b62c0, 0x16, 0x
a86740, ...)","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6908388,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/net/rpc/server.go:384 +0x14e","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6908464,"caller":"plugin/hclog_adapter.go:35","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6909401,"caller":"plugin/hclog_adapter.go:35","msg":"\t/usr/local/go/src/net/rpc/server.go:481 +0x42b","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"error","ts":1578687056.6925557,"caller":"mlog/log.go:174","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"com.github.matterpoll.matterpoll","error":"unexpected EOF"}
Jan 10 20:10:56 localhost mattermost[35696]: {"level":"debug","ts":1578687056.6925652,"caller":"plugin/hclog_adapter.go:33","msg":"plugin process exited","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"pathplugins/com.github.matterpoll.matterpoll/server/
dist/plugin-linux-amd64pid36132errorexit status 2"}
Jan 10 20:10:58 localhost mattermost[35696]: {"level":"debug","ts":1578687058.3124595,"caller":"web/handlers.go:77","msg":"Received HTTP request","method":"POST","url":"/api/v4/channels/members/me/view","request_id":"eo1bktjutjytpjyt4qb7emryoh"}
Jan 10 20:11:06 localhost mattermost[35696]: {"level":"debug","ts":1578687066.9889286,"caller":"plugin/supervisor.go:121","msg":"Error pinging plugin","error":"connection is shut down"}
Jan 10 20:11:06 localhost mattermost[35696]: {"level":"error","ts":1578687066.9894736,"caller":"plugin/health_check.go:90","msg":"Health check failed for plugin","id":"com.github.matterpoll.matterpoll","error":"Plugin RPC connection is not responding"}
Jan 10 20:11:06 localhost mattermost[35696]: {"level":"debug","ts":1578687066.989596,"caller":"plugin/health_check.go:109","msg":"Deactivating plugin due to multiple crashes","id":"com.github.matterpoll.matterpoll"}
Jan 10 20:11:06 localhost mattermost[35696]: {"level":"error","ts":1578687066.9896178,"caller":"mlog/log.go:174","msg":"RPC call OnDeactivate to plugin failed.","plugin_id":"com.github.matterpoll.matterpoll","error":"connection is shut down"}
Jan 10 20:11:06 localhost mattermost[35696]: {"level":"warn","ts":1578687066.9896407,"caller":"plugin/hclog_adapter.go:51","msg":"error closing client during Kill","plugin_id":"com.github.matterpoll.matterpoll","wrapped_extras":"errconnection is shut down"}
Jan 10 20:11:06 localhost mattermost[35696]: {"level":"warn","ts":1578687066.9896526,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"com.github.matterpoll.matterpoll"}
Jan 10 20:11:15 localhost mattermost[35696]: {"level":"debug","ts":1578687075.2095559,"caller":"app/email_batching.go:110","msg":"Email batching job ran. 0 user(s) still have notifications pending."}
:

```
</details>

#### Additional context
My mattermost install is default server language: polish

**Comment by amz** [comment]
After changing **Default Server Language:** in **Server console -> Localization** to English i can close poll.

**Comment by kaakaa** [comment]
Thank you for reporting @amz.
I could reproduce this in my local.

@hanzei 
This issue seems to be due to the difference of plural forms between languages.

Language "pl"  has the plural rule which returns "few" and "many", but [message file doesn't have plural forms for it](https://github.com/matterpoll/matterpoll/blob/master/assets/i18n/active.pl.json#L84). (Other language that Matterpoll can localize have only two plural rules "one" and "other", so those languages doesn't have this issue)

`nicksnyder/go-i18n` can fallback to "Other" pluralization in case the plural form is missing, but it results in returning `err` together with the message translated by "Other" pluralization.
https://github.com/nicksnyder/go-i18n/blob/f3faea2bc2dea8b799353f52fa3eb21fe146ec21/v2/i18n/localizer.go#L162

If `err` is returned, `localizer.MustLoalize` call `panic`, and this issue is happended.
https://github.com/nicksnyder/go-i18n/blob/f3faea2bc2dea8b799353f52fa3eb21fe146ec21/v2/i18n/localizer.go#L209

---

We should avoid using `localizer.MustLocalize`, because it calls `panic`.  Instead of it, 

```go
msg := localizer.MustLocalize(&i18n.LocalizeConfig{...})
```

we should use `localizer.Localize`. (but this form looks ugly...)

```go
msg, err := localizer.Localize(&i18n.LocalizeConfig{...})
if err != nil {
  // Logging err from go-i18n if possible
  p.API.LogWarn("Error occurs when translating message", "details", err.Error())
}
if len(msg) == 0 {
  // I want to set default message to `msg`, but it looks hard...
  msg := "..."
}
```

What do you think about this? Do you have any good idea? @hanzei

**Comment by hanzei** [comment]
I've opened https://github.com/matterpoll/matterpoll/pull/259 as a short term for the issue.

I also filled https://github.com/matterpoll/matterpoll/issues/260 and https://github.com/matterpoll/matterpoll/issues/261 to help avoid this issues in the future.
